name: Purge jsDelivr cache

on:
  workflow_dispatch:   # <-- ДОБАВЬТЕ ЭТУ СТРОКУ
  push:
    paths:
      - 'Sites.yaml'
    branches:
      - main

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        run: |
          curl -X GET "https://purge.jsdelivr.net/gh/BloodWolfik/Sites@main/Sites.yaml"
